//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashBookApp.WinForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int PaymentID { get; set; }
        public System.DateTime PaymentTime { get; set; }
        public decimal Amount { get; set; }
        public int PaymentTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsExpense { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
