
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CashBookApp.WinForm.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {

        this.OrderDetail = new HashSet<OrderDetail>();

    }


    public int ProductID { get; set; }

    public string Barcode { get; set; }

    public string ProductName { get; set; }

    public decimal Price { get; set; }

    public Nullable<decimal> InstallmentPrice { get; set; }

    public string Size { get; set; }

    public string Color { get; set; }

    public Nullable<int> Quantity { get; set; }

    public System.DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetail { get; set; }

}

}
